### ISSUE TITLE
Kairos Android Sdk Example missing

### ISSUE THREAD

**Issue by amna-mirza-11** [kairosinc/api-examples#22]
I have been working on Kairos Android SDK since Nov, 2018. Now, Suddenly I found that android sdk example is not available on git-hub. Any 1 can help with complete demonstrated example of android. If available provide link to project.

**Comment by coleca** [comment]
Hi

Yes we removed it because it hadn’t been updated in some time, we received some complaints about issues with it and we don’t currently have an Android dev on staff to maintain it. 

If you would like a copy of the source we will be happy to share it as is. Just send an email to support@kairos.com and we can send it to you.
