### ISSUE TITLE
Docker Install Issue?

### ISSUE THREAD

**Issue by gkodikara** [kairosinc/api-examples#4]
Hi,

Tried running this with 'make build && make run' and I get the following error:

```
Post http:///var/run/docker.sock/v1.20/build?cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&memory=0&memswap=0&rm=1&t=demo&ulimits=null: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
make: *** [build] Error 1
```

I've looked around as to why this is occuring but get led in circles, any idea what I need to do to resolve?

**Comment by coleca** [comment]
Hi

That usually means that the Docker daemon is not running on your system for some reason.  Try doing a `docker ps` from the command line.  You should get no errors.  Otherwise Docker is not installed correctly, or is not started.  

The Docker API you're using, 1.20, is also a pretty old version (Docker 1.8).  Might be worthwhile upgrading to Docker 1.13, although that shouldn't matter for this.
